name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}} (${{matrix.os}})
    strategy:
      fail-fast: false
      matrix:
        java-version: [11]
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: ./gradlew test
  release:
   needs: [test]
   if: "github.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/tags/')"
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - uses: actions/setup-java@v2
       with:
         distribution: 'adopt'
         java-version: 11
     - run: |
         mkdir -p ~/.gradle
         echo "sonatypeUsername=${{ secrets.SONATYPE_USERNAME }}" >> ~/.gradle/gradle.properties
         echo "sonatypePassword=${{ secrets.SONATYPE_PASSWORD }}" >> ~/.gradle/gradle.properties
         echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> ~/.gradle/gradle.properties
         echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties
         echo ${{ secrets.PGP_SECRET }} | base64 --decode | gpg --batch --import
         gpg -s --batch --pinentry-mode loopback --passphrase ${{ secrets.PGP_PASSPHRASE }}
     - name: Publish
       run: ./gradlew publishToSonatype closeSonatypeStagingRepository -Psigning.gnupg.executable=gpg -Psigning.gnupg.keyName="1977A26A5D2A8BCA" -Psinging.gnupg.passphrase=${{ secrets.PGP_PASSPHRASE }}
